### ISSUE TITLE
Suggestion: Guide document in get involved page.

### ISSUE THREAD

**Issue by avinashbharti97** [codeuino/website-www.codeuino.org#12]
In [get involved page](https://fossworld1.github.io/website-www.fossworld.org/getinvolved.html)  [Guide](https://github.com/FOSSWorld1/website-www.fossworld.org/blob/master/guides/code.md) is linked to a large image, It will look good if:

1.  A Download button to download that file is created
2. A markdown Reader is integrated so that .md file is visible there
3. Else can convert that .md file in HTML page

**Comment by jaskirat2000** [comment]
Thanks . this would be great. I guess we should have proper guide on how to contribute with proper markdown like this [http://api.coala.io/en/latest/Developers/Newcomers_Guide.html]
@im-gozmit , @ayushnagar123 and @Pratul1997 can you help in this?

**Comment by im-gozmit** [comment]
@jaskirat2000  Yepp I am working on writing a newcomer's guide. Yes a download button is a good idea (@avinashbharti97 ) and for markdown we can create an issue so someone interested in converting markdown file to html can work on it.

**Comment by sarthak77** [comment]
Is someone working on this issue?
If not can I take it up?

**Comment by jaskirat2000** [comment]
We already have few improvements required
http://www.codeuino.org/getInvolved.html

**Comment by sarthak77** [comment]
OK
I'll look for another one
Thanks anyways

**Comment by nik72619c** [comment]
Still free to work?

**Comment by sarthak77** [comment]
Yeah currently free
