### ISSUE TITLE
Interested in RGSoC. I know it won't happen this year :p This is just my intro.

### ISSUE THREAD

**Issue by sunn-e** [codeuino/website-www.codeuino.org#137]
Hey everyone. I'm @sunn-e from Nagpur, Maharashtra, India. I saw this project on under RGSoC's projects list. I'm happy to help to improve this site. I visited the official site of codeuino,org and noticed it does not have a security certificate. I know a free way to get a security certificate. This would be my first contribution as a new contributer. Will that be fine by the mentor(s)?  
<img width="769" alt="codeuino" src="https://user-images.githubusercontent.com/30065288/59192190-4da17a80-8b9f-11e9-9b1d-b3ad29b6ddb5.png">

**Comment by sunn-e** [comment]
Is it only for girls?

**Comment by jaskirat2000** [comment]
Hey thanks for reaching out.
It is open to all. Make sure you join our slack channel here at
slack.codeuino.org where all conversation takes place.

Thanks

**Comment by sunn-e** [comment]
Did. Thanks.
