### ISSUE TITLE
Making component of team page 

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/website-www.codeuino.org#179]
Problem:-The code of card content is repetitively written in src/pages/Team/Team.js . This does  not justify the idea of components in react.
 
![Screenshot from 2020-01-28 22-42-34](https://user-images.githubusercontent.com/37747717/73288014-398ab600-4220-11ea-9c1c-fa5ba664a080.png)

Solution:-Make use of react component and inject relevant properties as props.

**Comment by lakshyabatman** [comment]
I am working on it.

**Comment by lakshyabatman** [comment]
#180 solves this.
