### ISSUE TITLE
Edit README.md 

### ISSUE THREAD

**Issue by im-gozmit** [codeuino/website-www.codeuino.org#18]
As we have changed our name from FOSSWORLD to CODEUINO so someone please update the changes in the README.md and also add the some further contents in the README file, like : 
1. Languages we have used :HTML , CSS and JS
2. Procedure for someone who wants to contribute to the website.(fork, add,commit,pull request)
3. Slack channel link

**Comment by HarendraSingh22** [comment]
Anyone working on this?

**Comment by jaskirat2000** [comment]
No , no one is working for now

**Comment by im-gozmit** [comment]
@aryan-harsh  it is open and the task is to add the "steps to deploy the website locally" like starting with forking the repository to cloning and ending with submitting PR after making the changes.

**Comment by sourabh1031** [comment]
@im-gozmit I would like to work on the issue
