### ISSUE TITLE
Create a scroll to top component

### ISSUE THREAD

**Issue by JanviMahajan14** [codeuino/website-www.codeuino.org#185]
Currently the website doesn't have any component which makes it easy for the user to move at the top of the webpage

**Comment by JanviMahajan14** [comment]
@jaskirat2000 @Rupeshiya @ayushnagar123  I would like to start contributing to the community. Can I move ahead to solve this issue?

**Comment by jaskirat2000** [comment]
Sure. Go ahead for this
