### ISSUE TITLE
Pagination in Blog page is redirecting to the home page instead of next Bloglist

### ISSUE THREAD

**Issue by aryamanpuri** [codeuino/website-www.codeuino.org#186]
Steps to produce the behavior:

1. Go to http://localhost:3000/#/bloglist
2. Click on any page in the pagination down the page
3. It will redirect you to http://localhost:3000/#/

Instead of this, we should redirect the person to the same page 
@jaskirat2000 

![Screenshot from 2020-02-02 00-59-03](https://user-images.githubusercontent.com/43513114/73597935-c81c7180-4557-11ea-8f5c-a2d9070dfa99.png)

**Comment by jaskirat2000** [comment]
Thanks. Will get to this issue

**Comment by Rupeshiya** [comment]
@aryamanpuri Please update your development branch with the latest commits, since it's not the issue in new code.
I am sure you are using old code by looking at the header padding which was more then, and now it's fixed, look at the page below:
![bl](https://user-images.githubusercontent.com/31209617/73603763-4ce5aa80-45ad-11ea-8c09-1860f00477e0.png)

**Comment by aryamanpuri** [comment]
Latest code :
Still redirecting you to http://localhost:3000/#/
![Screenshot from 2020-02-02 14-55-38](https://user-images.githubusercontent.com/43513114/73606063-3864da80-45cc-11ea-86b9-76edb042d4f6.png)

**Comment by Rupeshiya** [comment]
@aryamanpuri Please run "git log --oneline" on your development branch and send me the screenshot.
Yes screenshot of code is correct, but it's not redirecting to http://localhost:3000/#/
it will redirect you to the same page http://localhost:3000/bloglist#

**Comment by aryamanpuri** [comment]
Solved , thanks @Rupeshiya 
![Screenshot from 2020-02-02 15-59-19](https://user-images.githubusercontent.com/43513114/73606866-0dcb4f80-45d5-11ea-8f7a-92bfd4b45f9a.png)

**Comment by Rupeshiya** [comment]
@jaskirat2000 Please close this issue
