### ISSUE TITLE
Displaying "latest Blogs" from the medium on the Home page.

### ISSUE THREAD

**Issue by jaskirat2000** [codeuino/website-www.codeuino.org#196]
Codeuino has its Blogs located on the [**medium**](https://medium.com/codeuino).
So the purpose of this issue is to Retrieve "Latest Blogs" from the Codeuino medium and show them on the Home Page under the **"Activities"** Section.

Currently, under the "**Activities**" Section on the Home page of [Codeuino Website](http://codeuino.org/) those are test data but it has to be linked with the medium account so that latest blogs which are published on the medium gets displayed here.

here is the screenshot for it and also reduce the size of that section.
![2222222222222222222](https://user-images.githubusercontent.com/10228651/74551676-99e85a00-4f79-11ea-8ce8-761c84351e25.PNG)

**Comment by lakshyabatman** [comment]
On it!

**Comment by Salmankhancodes** [comment]
> On it!

if it's available will you please assign it to me.??

**Comment by Salmankhancodes** [comment]
> Codeuino has its Blogs located on the [**medium**](https://medium.com/codeuino).
> So the purpose of this issue is to Retrieve "Latest Blogs" from the Codeuino medium and show them on the Home Page under the **"Activities"** Section.
> 
> Currently, under the "**Activities**" Section on the Home page of [Codeuino Website](http://codeuino.org/) those are test data but it has to be linked with the medium account so that latest blogs which are published on the medium gets displayed here.
> 
> here is the screenshot for it and also reduce the size of that section.
> ![2222222222222222222](https://user-images.githubusercontent.com/10228651/74551676-99e85a00-4f79-11ea-8ce8-761c84351e25.PNG)

if it's available will you please assign this task to me..?

**Comment by jaskirat2000** [comment]
Sure, go ahead
