### ISSUE TITLE
Tweets card are too big.

### ISSUE THREAD

**Issue by lakshyabatman** [codeuino/website-www.codeuino.org#198]
**Issue details**
The tweets card are way big,  compromising with the aesthetics of the website.
Though it looks perfect in smaller screens

**Task/ Solution**
To implement max-width in CSS to make tweet cards look better for larger screens.

Assigning this task to myself.

<img width="1440" alt="Screenshot 2020-02-25 at 1 59 07 PM" src="https://user-images.githubusercontent.com/29687362/75229137-5a223d80-57d7-11ea-8244-a578942e45e2.png">

**Comment by Abhik1998** [comment]
Okay, so what should be the max-width? Any suggestions? Like what proportion of the screen

**Comment by jaskirat2000** [comment]
Just single row with three columns can work.
