### ISSUE TITLE
Increase the size and Boldness of FOSSWorld name top left

### ISSUE THREAD

**Issue by jaskirat2000** [codeuino/website-www.codeuino.org#2]
we need to Increase the size and Boldness of FOSSWorld situated top left without disturbing the other content in same row

**Comment by Saichethan** [comment]
Actually, if there is a logo it would be better in that place so, I think let it be in that place until the logo is ready
Let me know if you are thinking differently

**Comment by jaskirat2000** [comment]
okay but i guess we need to make a logo in the same sense that looks fine on header

**Comment by Saichethan** [comment]
@aksharanigam1112  fixed this with PR #28
