### ISSUE TITLE
Wikipedia page

### ISSUE THREAD

**Issue by Saichethan** [codeuino/website-www.codeuino.org#23]
It's better if we have a Wikipedia page for Codeuino this helps in indexing site and forming rich cards so, interested people please start working on it.

**Comment by jaskirat2000** [comment]
Sounds good, i will make that so that others can also contribute there

**Comment by devshiva619** [comment]
@jaskirat2000 can we close this one?

**Comment by jaskirat2000** [comment]
@saichethan can you help us writing in this ?

**Comment by Saichethan** [comment]
@jaskirat2000 I tried many times but it went into speedy deletion category and my draft was reverted back by maintainers

**Comment by jaskirat2000** [comment]
Can you let me know the cause? Do you have a draft for it ?
