### ISSUE TITLE
Navbar should be fixed on the top 

### ISSUE THREAD

**Issue by AshishkrGoyal** [codeuino/website-www.codeuino.org#25]
![image](https://user-images.githubusercontent.com/25322851/41769818-2bd24588-762e-11e8-8654-565530365b87.png)
navbar must be fixed at the top while scrolling it will enhance the user experience !

**Comment by Saichethan** [comment]
@AshishkrGoyal wait for some time we don't have so much of content now it works fine
For projects, sponsors, mentors pages we may need that

**Comment by AshishkrGoyal** [comment]
@Saichethan please read the heading of issue again here i want to point out that navigation bar should be fixed on the top of the website !
it is a good practice for user experience to access the navigation bar at any time rather than to scroll over the site !

Thanks !

**Comment by Saichethan** [comment]
@AshishkrGoyal 
Yes! I read heading and I got it
if you want to work on this keep that header in a div and make it fixed. 
It's good practice but only when you have a lot to scroll
open a PR we will see that

Note: Suggestion watch your language

**Comment by Saichethan** [comment]
It's done!

**Comment by jaskirat2000** [comment]
@AshishkrGoyal and @Saichethan and @im-gozmit please solve this issue , thanks

**Comment by Saichethan** [comment]
@jaskirat2000  done!  I fixed navigation
I think now we can close this issue
