### ISSUE TITLE
Creating Markdown of beginner guide 

### ISSUE THREAD

**Issue by Saichethan** [codeuino/website-www.codeuino.org#32]
There is a need for making a beginner's guide for newcomers to make them familiar with our workflow 

reference : https://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by im-gozmit** [comment]
@Saichethan  assign this to @aksharanigam1112

**Comment by Saichethan** [comment]
@im-gozmit  I already did but I can't find her name in assign tab
