### ISSUE TITLE
Website Content

### ISSUE THREAD

**Issue by Saichethan** [codeuino/website-www.codeuino.org#33]
As our community is rapidly growing some of the content in it should be updated. There is also need for good content about codeuino both technically and as an organisation

Please comment if you are interested

**Comment by aryan-harsh** [comment]
@Saichethan can you give a little more detail about what to do?

**Comment by jaskirat2000** [comment]
We are looking for a writer who can write up good description about things
after understanding them

**Comment by Saichethan** [comment]
@aryan-harsh if are interested in this issue feel free to work on it.

**Comment by ayonroy2000** [comment]
Trying to work on this issue .

**Comment by ayonroy2000** [comment]
@jaskirat2000 , I can try my hand to write good description after understanding the things !!

**Comment by vaibhavdaren** [comment]
@ayonroy2000  you may work on it :+1:

**Comment by ayonroy2000** [comment]
Could you please guide me about how to proceed as its my first time . 
I shall be obliged towards you if you get in touch with me on ayon.roy2000@gmail.com and make me understand the things that I have to do in  a clearer manner .

**Comment by jaskirat2000** [comment]
That would be great lets get on a conference hangout video call when you
are comfortable...i can help you to understand about the community
bonding,plans,vision,etc

These things will be required to document here
