### ISSUE TITLE
embedding bootstrap in index.html

### ISSUE THREAD

**Issue by capedcrusader23** [codeuino/website-www.codeuino.org#34]
To solve the issue of  contributor we had to embed bootstrap.min.css inside index.html
Placing cdn above main.css make about us section disappear and same is case when we place this bootstrap.min.css file below main.css.
This is not working
![capture](https://user-images.githubusercontent.com/37747717/42013142-b2c03e80-7a50-11e8-804d-dfd98989d4e6.PNG)
This is also not working 
![capture](https://user-images.githubusercontent.com/37747717/42013186-f4e304b4-7a50-11e8-9336-129af5b77a85.PNG)

**Comment by jaskirat2000** [comment]
Are you deploying this on your local machine ? Did you try making a new branch and code directly here on GH ?

**Comment by capedcrusader23** [comment]
yep i did it on my local machine

**Comment by aryan-harsh** [comment]
@capedcrusader23  issue still there?

**Comment by jaskirat2000** [comment]
Yes it is there .nour board is trying to resolve this

**Comment by aryan-harsh** [comment]
well if someone is working , i'll find another issue. Thanks

**Comment by Saichethan** [comment]
It's just because his bootstrap Assets conflicts with website Assets

**Comment by hardy1334** [comment]
Yeah,I also tried using bootstrap but many parts of webpage stops working
