### ISSUE TITLE
Navbar color should become white on scrolling and should remain fixed

### ISSUE THREAD

**Issue by jaskirat2000** [codeuino/website-www.codeuino.org#35]
Navbar color should become white on scrolling and should remain fixed

**Comment by jaskirat2000** [comment]
@HarendraSingh22 and @avinashbharti97

**Comment by Saichethan** [comment]
Navigation is already fixed and white

**Comment by aryan-harsh** [comment]
@Saichethan anything to improve about the navbar?

**Comment by avinashbharti97** [comment]
**I Tried fixing this using Jquery scroll function**

``$(window).scroll(function() {
		if ($(document).scrollTop() > 50) {
				$('#header').addClass('color-change');
		} else {
				$('#header').removeClass('color-change');
		}
});


**but getting this error in firefox browser**

![scroll](https://user-images.githubusercontent.com/22724583/42069075-462752fe-7b6d-11e8-9a7b-1939830a450d.png)
