### ISSUE TITLE
Implement Slack invitation

### ISSUE THREAD

**Issue by devshiva619** [codeuino/website-www.codeuino.org#49]
As of now after writing the email id and clicking on join us does not do anything.
Make it functional so that a user when inputs his/her email id and click the join us button they are sent the slack invitation.

![slack-invite-screenshot](https://user-images.githubusercontent.com/20336672/42591787-5ec7dea8-8565-11e8-9665-e04ae4d9b45e.png)

**Comment by jaskirat2000** [comment]
maybe this could be helpful [https://stackstorm.com/2015/06/30/using-stackstorm-to-auto-invite-users-to-a-slack-organization/](url)

**Comment by sourabh1031** [comment]
@devshiva619 @jaskirat2000 I would like to work on this please tell me what is expected from me. Actually, i want to know what things are required as a prerequisite to work on this

**Comment by jaskirat2000** [comment]
Thanks man...this issue is already resolved
You can work on other issues.
Good luck
