### ISSUE TITLE
Slow loading of the site

### ISSUE THREAD

**Issue by khanna98** [codeuino/website-www.codeuino.org#51]
The site takes a lot of time to load as compared to other websites

**Comment by jaskirat2000** [comment]
How can it be improved maybe you can help us !!?

**Comment by khanna98** [comment]
I will try it :+1:

**Comment by jaskirat2000** [comment]
Ok

**Comment by shubhiD** [comment]
Can I help too? But I am a noob, please bear with me :)

Proposed things, do let me know if you agree:
1) We can combine all css in one file and all js in another and deliver minified version of these, this will improve the number of request. Is this feasible?
2) We can leverage browser caching to deliver static files
3) We must losslessly compress every image we show on our site ( currently we can save about 27kbs of data, but we should adhere to this, it will be helpful in longer run )
4) The following url is a 404 http://codeuino.org/images/code.png please update this link, such links must not be there, won't improve much on speed but good practice
5) We can set expiry headers -> There are 28 static components without a far-future expiration date

I feel most important is to reduce HTTP requests by combining js files in one and css files in one and also losslessly compressing images

Please tell if the proposed plan is good or we can discuss further

**Comment by jaskirat2000** [comment]
@shubhiD Thanks for reaching out. This sounds really good but i don't think compressing the image file is good as it will reduce our impact on virtual categories. So i suggest you to move further and help us to resolve this issue.

Thanks

**Comment by jaskirat2000** [comment]
@devshiva619

**Comment by shubhiD** [comment]
Lossless compression will have not much effect on visual categories. We can
compare too side by side the image quality. Actually this issue hampered
performance during my internship period with a startup. That time we had
too many images so we could see the difference. And I also think we should
shift to SVG images wherever we can (for icons and stuff), this is really
good for performance and SEO. More details here
https://imagekit.io/blog/svg-optimization-improves-website-speed/

**Comment by shubhiD** [comment]
I dont know if you know but there is this tool that helps a lot in optimising the site as it provide suggestions too more infor about performance issue on the site here https://gtmetrix.com/reports/www.codeuino.org/UUpc5Wuh

**Comment by jaskirat2000** [comment]
@shubhiD sounds good to me this How to proceed for it > your opinion ?

**Comment by shubhiD** [comment]
https://gtmetrix.com/reports/www.codeuino.org/UUpc5Wuh you can find the images that can be losslessly compressed on this tool, you can replace the current images with these, and we can make sure anytime new image is requires it is losslessly compressed with any online tool, we can convert icons or images in which colors do not change much to svg's

**Comment by shubhiD** [comment]
how about creating a script that would see if an image is already compressed or not and if not would compress it?
