### ISSUE TITLE
wrong practice (css)

### ISSUE THREAD

**Issue by shubhiD** [codeuino/website-www.codeuino.org#57]
https://github.com/codeuino/website-www.codeuino.org/blob/69b6aec5914dff5965452fc070188658203c4f56/css/style.css#L1859

please change to some meaningful class like ".color-white" or something else and use accordingly, this high level tag selector will create problem. It is already creating problem for slack Join Us input tag.

**Comment by jaskirat2000** [comment]
@devshiva619

**Comment by aganjali10** [comment]
I would like to work on this issue.

**Comment by devshiva619** [comment]
@aganjali10 sure go ahead :+1:
