### ISSUE TITLE
Unexpected results on mouse hovering

### ISSUE THREAD

**Issue by aastha980** [codeuino/website-www.codeuino.org#60]
When we hover the mouse on recent products headings then unexpected result is obtained.

![hover1](https://user-images.githubusercontent.com/29335511/44137766-3a2eb798-a08f-11e8-9fa2-79b861d5b273.JPG)

On hovering this result is obtained. However we want the correct padding of text displayed on hover.
![hover2](https://user-images.githubusercontent.com/29335511/44137865-8bc5af3a-a08f-11e8-98c3-e3e391087b52.JPG)

**Comment by jaskirat2000** [comment]
This whole page needs to be reframed
