### ISSUE TITLE
Add a Contributor page with ".html" file.

### ISSUE THREAD

**Issue by jaskirat2000** [codeuino/website-www.codeuino.org#87]
Add a Contributor page with ".html" file with the names and images in the circles.

**Comment by sourabh1031** [comment]
@jaskirat2000 i would like to work on it

**Comment by jaskirat2000** [comment]
Okay sure ..go on ..it would be great

**Comment by sourabh1031** [comment]
@jaskirat2000 please tell me how do i reproduce the issue

**Comment by jaskirat2000** [comment]
I am not sure what you are tdying to say but If you are planning to create
new issue then there is a button on top in green color when you click on
issue tab

And

If you are planning to work on this issue then read the description about
this particular issue...write code and then make a PR as well as comment on
this issue that you made a PR.
