### ISSUE TITLE
Donate Us button not working

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [codeuino/website-www.codeuino.org#89]
The hovering Donation Panel comes up when I click the Donate Us option from the nav bar.
If I click the cross on the top right panel of the hovering Donation Panel, Donate Us area of the page is visible, but the red Donate Us button on its center isn't working.
Nothing happens when clicked.

Ideally, the Donate Us area of the page should come up when selected from Nav Bar.
The Donate Us panel can be hovered on being clicked on the red Donate Us button.

**Comment by Ridvmodi** [comment]
fixed this issue check PR #104 @jaskirat2000 @vaibhavdaren

**Comment by imskr** [comment]
I would like to work on it!  Can I add the PayPal button instead of red button?  
I guess PayPal button is more professional.

**Comment by jaskirat2000** [comment]
You can give another option as paypal button

**Comment by imskr** [comment]
Ok should I add it behind the red button?
