### ISSUE TITLE
Too less projects to view

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [codeuino/website-www.codeuino.org#92]
In the Projects section, when the numbers are clicked, the page is refreshed.
Basically, there are too less projects on the website to view.

**Comment by Vibhu-Agarwal** [comment]
Possible solution could be to dynamically add your projects.
You can use the github api and pick up the data of your from the repositories and display as the mainatainers like it.
Make sure to use the authorized github api endpoints as the unauthorized github api endpoints have a rate limit of just 60 hits per hour.

**Comment by jaskirat2000** [comment]
thanks @Vibhu-Agarwal for taking this up but we are currently under process of a new website which is being developed here https://github.com/codeuino/website-V2 the code is in the local machines of developers and yet to be committed.

**Comment by Vibhu-Agarwal** [comment]
Oh! You can add this information in the Readme file of this repository so that contributors aware about the new website and start contributing there :)

**Comment by jaskirat2000** [comment]
Okay thanks
